platform :ios, '8.0'
use_frameworks!

target 'ProjectOxfordFace_Example' do
    pod 'ProjectOxfordFace'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD'
    pod 'Firebase/Storage'
    pod 'Firebase/Core'
end


target 'ProjectOxfordFace_Tests' do
    inherit! :search_paths

end

post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
end


